Feature/render api
engineer-boys/espert-core pull request #12
Opened 2023-10-17 19:07 UTC by sebastianSzarafin

2023-10-17 22:46 UTC, DawidSzpejna commented
WTF, did you really change/add 65 files??? You are crazy, bro...

2023-10-17 23:02 UTC, DawidSzpejna commented
Well, I'll still be grumpy, but in this branch you have more than just the Render API. You even admit it, because there are more directories than `VulkanRenderAPI`. Something wnet wrong?

2023-10-18 21:35 UTC, kubo11 requested changes

2023-10-18 21:35 UTC, kubo11 commented on CMakeLists.txt
> +include_directories(${PROJECT_SOURCE_DIR}/src/Core)
Including ${PROJECT_SOURCE_DIR}/src should be enough. There are no header files outside of it.

2023-10-18 21:35 UTC, kubo11 commented on CMakeLists.txt
> +    set(SPIRV "${PROJECT_SOURCE_DIR}shaders/${FILE_DIR}/${FILE_NAME}.spv")
Why was this character removed? Won't it cause errors?

2023-10-18 21:35 UTC, kubo11 commented on CMakeLists.txt
> -)
Why was this target removed? Now add_dependencies will throw errors because there is no shaders target.

2023-10-18 21:35 UTC, kubo11 commented on src/Core/EspWindow.hh
> +#include "volk.h"
I cannot find the source right now, but I have read that you should include volk before including glfw and should't define GLFW_INCLUDE_VULKAN at all.

2023-10-18 21:35 UTC, kubo11 commented on src/Core/Layers/LayerStack.hh
> +	  std::vector<Layer*>::iterator _m_head_of_normall_layers;
Typo: _head_of_normal_layers

2023-10-20 16:25 UTC, kubo11 approved these changes

2023-10-20 16:25 UTC, merged