RenderAPI V2 [DON'T MERGE]
engineer-boys/espert-core pull request #39
Opened 2023-12-17 16:51 UTC by DawidSzpejna

In progress ............................................

2023-12-18 22:15 UTC, sebastianSzarafin commented on src/Core/Application.cc
> +
linijeczka

2023-12-18 22:29 UTC, sebastianSzarafin commented on src/Core/EspWindow.hh
> +      const bool m_resizable      = true;
ja bym zrobił jakąś strukturkę typu WindowParams która będzie zawierała takie rzeczy konfiguracjne i wrzucił ją w konstruktor

2023-12-18 23:02 UTC, sebastianSzarafin commented on src/Platform/Vulkan/Work/VulkanWorkOrchestrator.hh
> +    /* -------------------------- METHODS STATIC --------------------------- */
Dawid mówi się STATIC METHODS

2023-12-19 12:39 UTC, kubo11 requested changes

2023-12-19 16:41 UTC, DawidSzpejna commented on src/Core/Application.hh
> +    Application(const std::string title = "Espert window", unsigned int width = 1280, unsigned int height = 720);
I don't understand this evil language

2023-12-19 16:41 UTC, DawidSzpejna commented on src/Core/EspWindow.cc
> +  // }
this must be here

2023-12-19 19:30 UTC, kubo11 commented on src/Core/Application.hh
> +    Application(const std::string title = "Espert window", unsigned int width = 1280, unsigned int height = 720);
kk

2023-12-19 22:04 UTC, kubo11 approved these changes

2023-12-19 22:05 UTC, merged